### ISSUE TITLE
Using sanitizer before pass HTML string to dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by ryanrw** [rayriffy/ywc17-chimp#1]
If you enter your site you would found this.
![img](https://i.imgur.com/D5tjV8m.png)

Using dangerouslySetInnerHTML should sanitizer the HTML string first. It only reminds you that directly set InnerHTML would be dangerous.
I suggest using sanitizer like DOM Purify would do its job. 😎

**Comment by ryanrw** [comment]
ref: https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by rayriffy** [comment]
Closed at 1b665e9533c76eabfd4ba9e1998781c37f861a8c
